import { type NextRequest, NextResponse } from "next/server"
import { createServerClient } from "@supabase/ssr"
import { cookies } from "next/headers"
import jsPDF from "jspdf"

export async function POST(request: NextRequest) {
  try {
    const cookieStore = cookies()
    const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
      },
    })

    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await request.json()
    const { alertId, incidentDescription, assignedOfficer } = body

    // Generate E-FIR using database function
    const { data: firId, error: firError } = await supabase.rpc("generate_efir", {
      alert_id_param: alertId,
      incident_description: incidentDescription,
    })

    if (firError) {
      console.error("E-FIR generation error:", firError)
      return NextResponse.json({ error: "Failed to generate E-FIR" }, { status: 500 })
    }

    // Update with assigned officer if provided
    if (assignedOfficer) {
      await supabase.from("efir_records").update({ assigned_officer: assignedOfficer }).eq("id", firId)
    }

    // Get complete E-FIR data for PDF generation
    const { data: efirData } = await supabase
      .from("efir_records")
      .select(`
        *,
        alerts:alert_id (
          *,
          profiles:user_id (
            full_name,
            email,
            phone
          )
        ),
        assigned_officer_profile:assigned_officer (
          full_name,
          email
        )
      `)
      .eq("id", firId)
      .single()

    // Generate PDF
    const pdfBuffer = await generateEFIRPDF(efirData)

    return NextResponse.json({
      firId,
      firNumber: efirData.fir_number,
      pdfUrl: `data:application/pdf;base64,${pdfBuffer.toString("base64")}`,
      message: "E-FIR generated successfully",
    })
  } catch (error) {
    console.error("E-FIR generation error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

async function generateEFIRPDF(efirData: any): Promise<Buffer> {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.text("ELECTRONIC FIRST INFORMATION REPORT (E-FIR)", 20, 30)

  doc.setFontSize(12)
  doc.text(`FIR Number: ${efirData.fir_number}`, 20, 50)
  doc.text(`Date: ${new Date(efirData.created_at).toLocaleDateString()}`, 20, 60)
  doc.text(`Time: ${new Date(efirData.created_at).toLocaleTimeString()}`, 20, 70)

  // Complainant Details
  doc.setFontSize(14)
  doc.text("COMPLAINANT DETAILS:", 20, 90)
  doc.setFontSize(12)

  const complainant = efirData.complainant_details
  doc.text(`Name: ${complainant.name || "N/A"}`, 20, 105)
  doc.text(`Email: ${complainant.email || "N/A"}`, 20, 115)
  doc.text(`Phone: ${complainant.phone || "N/A"}`, 20, 125)

  // Incident Details
  doc.setFontSize(14)
  doc.text("INCIDENT DETAILS:", 20, 145)
  doc.setFontSize(12)

  doc.text(`Alert Type: ${complainant.alert_type || "N/A"}`, 20, 160)
  doc.text(`Severity: ${complainant.severity || "N/A"}`, 20, 170)

  // Incident Description
  const description = efirData.incident_details || "No description provided"
  const splitDescription = doc.splitTextToSize(description, 170)
  doc.text("Description:", 20, 185)
  doc.text(splitDescription, 20, 195)

  // Location
  if (efirData.location) {
    doc.text("Location: Coordinates available in system", 20, 220)
  }

  // Assigned Officer
  if (efirData.assigned_officer_profile) {
    doc.setFontSize(14)
    doc.text("ASSIGNED OFFICER:", 20, 240)
    doc.setFontSize(12)
    doc.text(`Name: ${efirData.assigned_officer_profile.full_name}`, 20, 255)
    doc.text(`Email: ${efirData.assigned_officer_profile.email}`, 20, 265)
  }

  // Footer
  doc.setFontSize(10)
  doc.text("This is a computer-generated document. No signature required.", 20, 280)
  doc.text("Generated by Tourist Safety Monitoring System", 20, 290)

  return Buffer.from(doc.output("arraybuffer"))
}
